name: Build Helper with Dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 'helper' repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 for 'api' dependency
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build 'api' dependency (with JDK 21)
        run: |
          echo "Cloning and building 'api' dependency..."
          git clone https://github.com/libxposed/api.git
          cd api
          chmod +x gradlew
          ./gradlew publishToMavenLocal
          cd ..
          echo "'api' dependency built successfully."

      - name: Set up JDK 17 for 'helper' library
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build 'helper' library (with JDK 17)
        run: |
          chmod +x gradlew
          ./gradlew publishToMavenLocal

      - name: Upload Maven Repository Artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-repository-helper
          path: ~/.m2/repository/
